### PR TITLE
[EventsTab] add txn actions and use thala as an example

### PR DESCRIPTION
**Pull request by 0xbe1**
### Description

set up a template to add event interpretation (aka "action") to txn events tab, and add thalaswap actions as the first ones.

see https://deploy-preview-908--aptos-explorer.netlify.app/txn/1916163127?network=mainnet

image

### Related Links

#865 

### Checklist

- [x] Have you run `pnpm fmt`?

### CODE REVIEW

**Review by gregnazario — COMMENTED** [review]
My only thought here, maybe we pull these out of the events and onto the main page to be more helpful to the average user.

In this case, you can see here someone once upon a time, thought about this for NFT transfers / mints.  Maybe we can move it there?
https://explorer.aptoslabs.com/txn/1811127385?network=mainnet

**Comment by 0xbe1** [comment]
> My only thought here, maybe we pull these out of the events and onto the main page to be more helpful to the average user.
> 
> In this case, you can see here someone once upon a time, thought about this for NFT transfers / mints. Maybe we can move it there? https://explorer.aptoslabs.com/txn/1811127385?network=mainnet

are you ok with having "action" in both main page and events page?

**Comment by 0xbe1** [comment]
@gregnazario understood, moved it under txn page

**Review by gregnazario — APPROVED** [review]
Let's get everyone to add parsers!

Maybe we should write instructions

**Pull request merged**
