### PR TITLE
[Contract] Add Code snippets for Contract View and Run tab

### PR DESCRIPTION
**Pull request by SamuelQZQ**
This PR depends on #503, after #503 is merged, the code will automatically jump to the line of the function.

Add Code snippets:
image

Sort the packages by name
image

### CODE REVIEW

**Comment by jillxuu** [comment]
you might wanna rebase this pr to the main so that the change will be correctly reflected?

**Comment by SamuelQZQ** [comment]
You can test with: https://deploy-preview-509--aptos-explorer.netlify.app/account/0x1/modules/code/account/offer_signer_capability?network=devnet&feature=dev

**Review by 0xbe1 — APPROVED** [review]
lgtm

**Review by jillxuu — APPROVED** [review]
one small nit not relevant to this PR: can we actually remove "COPY CODE" and expand button when code's not available? doesn't look the best on the dark mode.

**Pull request merged**
